---
# requires params:
# version: tag/branch name of the target version
# install_path: target path for srsRAN installation
# commit: actual full commit hash
# uhd: uhd version

- name: '("{{ version }}"): Install dependencies'
  ansible.builtin.apt:
    install_recommends: false
    pkg:
       - cmake
       - make
       - gcc
       - g++
       - pkg-config
       - libfftw3-dev
       - libmbedtls-dev
       - libsctp-dev
       - libyaml-cpp-dev
       - libgtest-dev
    state: present
  become: true

- ansible.builtin.file:
    path: "{{ install_path }}"
    state: directory
- ansible.builtin.include_role:
    name: UHD
  vars:
    version: "{{ uhd }}"

- name: '("{{ version }}"): Clone srsRAN release'
  ansible.builtin.git:
    repo: "https://github.com/srsran/srsRAN_Project"
    clone: true
    dest: "{{ install_path }}"
    version: "{{ commit }}"
  become: false

- ansible.builtin.set_fact:
    git_root: "{{ install_path }}/"

- name: '("{{ version }}"): Compile SRS RAN - prepare build'
  ansible.builtin.file:
    dest: "{{ git_root }}/build"
    state: directory
  become: false

- name: '("{{ version }}"): Compile SRS RAN - cmake'
  ansible.builtin.shell:
    chdir: "{{ git_root }}/build"
    cmd: cmake ../
  become: false

- name: '("{{ version }}"): Compile SRS RAN - make (takes multiple minutes)'
  ansible.builtin.make:
    chdir: "{{ git_root }}/build"
    jobs: "{{ ansible_facts['processor_vcpus'] }}"
  become: false

# - name: '("{{ version }}"): Compile SRS RAN - make test'
#   ansible.builtin.make:
#     chdir: "{{ git_root }}/build"
#     target: test
#     jobs: "{{ ansible_facts['processor_vcpus'] }}"
#   become: false

