---

- name: Add Open5GS repo
  ansible.builtin.apt_repository:
    repo: 'ppa:open5gs/latest'
    state: present
  become: true

- name: Install Open5GS
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - open5gs
    state: present
  become: true

- name: Add node repo
  ansible.builtin.shell: |
     curl -fsSL https://deb.nodesource.com/setup_22.x | bash
  become: true

- name: Install Node
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - nodejs
    state: present
  become: true


- name: Add Open5GS WebUI
  ansible.builtin.shell: |
     curl -fsSL https://open5gs.org/open5gs/assets/webui/install | sudo -E bash -
  become: true

- name: Add host ip to service file
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/open5gs-webui.service
    regex: '^Environment=HOSTNAME'
    insertafter: '^Environment='
    line: '^Environment=HOSTNAME={{ hostvars[inventory_hostname].ansible_default_ipv4.address }}'
  become: true

- name: Reload services
  ansible.builtin.service:
     daemon_reload: true
  become: true

- name: Enable Open5GS WebUI
  ansible.builtin.service:
     name: open5gs-webui
     # enabled: true
     state: "started"
  become: true



