
- name: Install dependencies
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - uhubctl               # Used to powercycle the modem
      - tcpdump
      - python3-scapy
    state: present
  become: true

