
- name: Install dependencies
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - uhubctl               # Used to powercycle the modem
      - tcpdump
      - python3-scapy
      - lm-sensors
    state: present
  become: true

- name: Remove unattended upgrades
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - unattended-upgrades
    state: absent
  become: true

  # TODO: sudo apt install linux-tools-$(uname -r)
  # TODO: usb resetter
