
- name: Add tinkerforge APT repo
  block:
    - ansible.builtin.apt_key:
        url: https://download.tinkerforge.com/apt/ubuntu/tinkerforge.asc
        #dest: /etc/apt/trusted.gpg.d/tinkerforge.arc
        state: present
      become: true
    - ansible.builtin.apt_repository:
        repo: deb https://download.tinkerforge.com/apt/ubuntu noble main
        filename: tinkerforge
        state: present
      become: true
- name: Install apt packages
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - uhubctl               # Used to powercycle the modem
      - tcpdump
      - python3-scapy
      - python3-tinkerforge
      - lm-sensors
    state: present
    update_cache: true
  become: true

- name: Remove unattended upgrades
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - unattended-upgrades
    state: absent
  become: true

  # TODO: sudo apt install linux-tools-$(uname -r)
  # TODO: usb resetter
