- name: '"{{ item.identifier }}": stop jammer wrapper'
  ansible.builtin.shell: |
     sudo killall jammer-wrapper.py
  become: true
  async: 900
  poll: 0
  ignore_errors: true
  when: jammer is defined
  register: jammer_job
  delegate_to: 5g-core

- name: '"{{ item.identifier }}": killall running jammer instances'
  ansible.builtin.shell: |
     sudo systemctl stop jammer_api.service
  become: true
  ignore_errors: true
  delegate_to: 5g-core