---


- name: Get default config
  ansible.builtin.copy:
    src: ../config/gnb_config_baseline/oai.conf
    dest: "{{ gnb_oai_config_path }}"

- ansible.builtin.debug:
    msg:
    - "{{ item.gnb_bandwidth }}"
    - "{{ (item.gnb_bandwidth | type_debug) }}"

- name: Load configuration for current bandwidth
  ansible.builtin.set_fact:
    oai_arfcn_cfg: "{{ bandwidth_definitions[item.gnb_bandwidth].OAI }}"

- ansible.builtin.debug:
    msg:
    - "{{ oai_arfcn_cfg }}"

- name: "Set ARFCN values and other bandwidth dependent configuration"
  block:
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        absoluteFrequencySSB'
      line: "        absoluteFrequencySSB = {{ oai_arfcn_cfg.arfcn_sbb |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        dl_absoluteFrequencyPointA'
      line: "        dl_absoluteFrequencyPointA = {{ oai_arfcn_cfg.arfcn_pointa |int }};"

  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        dl_carrierBandwidth'
      line: "        dl_carrierBandwidth = {{ oai_arfcn_cfg.carrier_bandwidth_rb |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        ul_carrierBandwidth'
      line: "        ul_carrierBandwidth = {{ oai_arfcn_cfg.carrier_bandwidth_rb |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        initialDLBWPlocationAndBandwidth'
      line: "        initialDLBWPlocationAndBandwidth = {{ oai_arfcn_cfg.initalBWPlocationAndBandwidth }}; # 6366 12925 12956 28875 12952;"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        initialULBWPlocationAndBandwidth'
      line: "        initialULBWPlocationAndBandwidth = {{ oai_arfcn_cfg.initalBWPlocationAndBandwidth }}; # 6366 12925 12956 28875 12952;"



- name: "Edit OAI RAN config:"
  block:
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        nrofDownlinkSlots'
      line: "        nrofDownlinkSlots = {{ item.tdd_config.tdd_dl_slots |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        nrofDownlinkSymbols'
      line: "        nrofDownlinkSymbols = {{ item.tdd_config.tdd_dl_symbols |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        nrofUplinkSlots'
      line: "        nrofUplinkSlots = {{ item.tdd_config.tdd_ul_slots |int }};"
  - ansible.builtin.lineinfile:
      path: "{{ gnb_oai_config_path }}"
      search_string: '        nrofUplinkSymbols'
      line: "        nrofUplinkSymbols = {{ item.tdd_config.tdd_ul_symbols |int }};"

- when: item.tdd_config.tdd_period == 5
  ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '        dl_UL_TransmissionPeriodicity'
    line: "        dl_UL_TransmissionPeriodicity = 5;"
- when: item.tdd_config.tdd_period == 10
  ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '        dl_UL_TransmissionPeriodicity'
    line: "        dl_UL_TransmissionPeriodicity = 6;"
- when: item.tdd_config.tdd_period == 20
  ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '        dl_UL_TransmissionPeriodicity'
    line: "        dl_UL_TransmissionPeriodicity = 7;"



- name: "Set MCS limits to temp variables"
  block:
    - ansible.builtin.set_fact:
        min_dl_mcs: 0
        max_dl_mcs: 28
      when: item.dl_mcs == "None"
    - ansible.builtin.set_fact:
        min_dl_mcs: "{{ item.dl_mcs }}"
        max_dl_mcs: "{{ item.dl_mcs }}"
      when: item.dl_mcs != "None"
    - ansible.builtin.set_fact:
        min_ul_mcs: 0
        max_ul_mcs: 28
      when: item.ul_mcs == "None"
    - ansible.builtin.set_fact:
        min_ul_mcs: "{{ item.ul_mcs }}"
        max_ul_mcs: "{{ item.ul_mcs }}"
      when: item.ul_mcs != "None"
- ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '    dl_min_mcs    '
    line: "    dl_min_mcs = {{ min_dl_mcs }};"
- ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '    dl_max_mcs    '
    line: "    dl_max_mcs = {{ max_dl_mcs }};"
- ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '    ul_min_mcs    '
    line: "    ul_min_mcs = {{ min_ul_mcs }};"
- ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '    ul_max_mcs    '
    line: "    ul_max_mcs = {{ max_ul_mcs }};"


- when: item.rx_gain != None
  ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '    att_rx         = '
    line: "    att_rx = {{ 70.0 - item.rx_gain |int }};" # TODO: is this calculation correct? only for B210 if at all!
- when: item.tx_gain != None
  ansible.builtin.lineinfile:
    path: "{{ gnb_oai_config_path }}"
    search_string: '  att_tx         = '
    line: "    att_tx = {{ 89.75 - item.tx_gain |int }};" # TODO: is this calculation correct? only for B210 if at all!
