---
# version: tag/branch name of the target version
# Install path is known


- ansible.builtin.set_fact:
    install_path: "/home/gnb/gnb_versions/{{ version }}/UHD--{{ version }}"
- ansible.builtin.file:
    path: "{{ install_path }}"
    state: directory


- name: '("{{version}}"): Install dependencies'
  ansible.builtin.apt:
    install_recommends: false
    pkg:
      - autoconf
      - automake
      - build-essential
      - ccache
      - cmake
      - cpufrequtils
      - doxygen
      - ethtool
      - g++
      - git
      - inetutils-tools
      - libboost-all-dev
      - libncurses5
      - libncurses5-dev
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libusb-dev
      - python3-dev
      - python3-mako
      - python3-numpy
      - python3-requests
      - python3-scipy
      - python3-setuptools
      - python3-ruamel.yaml
    state: present
  become: true

- name: '("{{version}}"): Clone USRP Hardware Driver'
  ansible.builtin.git:
    repo: "https://github.com/EttusResearch/uhd.git"
    clone: true
    dest: "{{ install_path }}"
    version: "{{ version }}"
  become: false

- name: '("{{version}}"): Compile UHD - prepare build'
  ansible.builtin.file:
    dest: "{{ install_path }}/host/build"
    state: directory
  become: false

- name: '("{{version}}"): Compile UHD - cmake'
  ansible.builtin.shell:
    chdir: "{{ install_path }}/host/build"
    cmd: cmake ../
  become: true
  ignore_errors: true
# WARN: not an error: cmake fails for the first time for UHD-3.15.LTS in ansible (for some bizzare reason)
#  second time works
- name: '("{{version}}"): Compile UHD - cmake'
  ansible.builtin.shell:
    chdir: "{{ install_path }}/host/build"
    cmd: cmake ../
  become: true

- name: '("{{version}}"): Compile UHD - make (takes multiple minutes)'
  ansible.builtin.make:
    chdir: "{{ install_path }}/host/build"
    jobs: "{{ ansible_facts['processor_vcpus'] }}"
  become: true

- name: '("{{version}}"): Compile UHD - make test'
  ansible.builtin.make:
    chdir: "{{ install_path }}/host/build"
    target: test
    jobs: "{{ ansible_facts['processor_vcpus'] }}"
  become: true

- name: '("{{version}}"): Compile UHD - make install'
  ansible.builtin.make:
    chdir: "{{ install_path }}/host/build"
    target: install
  become: true

- name: '("{{version}}"): Compile UHD - setup library path'
  ansible.builtin.command:
    chdir: "{{ install_path }}/host/build"
    cmd: ldconfig
  become: true
