system:
    pcap_dump: ../dumps/
    identifier: 651c9a37
    fixed_params:
        distance_horizontal_in_m: 0.5
        distance_vertical_in_m: 0.34
        gnb_antenna_inclanation_in_degree: 90
        gnb_antenna_rotation_in_degree: 0
        ue_antenna_inclanation_in_degree: 90
        ue_antenna_rotation_in_degree: 0
        modem: SIM8200EA-M2 5G HAT
        interface_ue: wwan0
        interface_gnb: eno1
        jammer: true
run_to_run_variation:
# -   identifier: 651c9a37__b9ec89e4__000
#     run: 0
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-3.15.LTS
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__b9ec89e4__001
#     run: 1
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-3.15.LTS
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__ef87ecf7__000
#     run: 0
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-3.15.LTS
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__ef87ecf7__001
#     run: 1
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-3.15.LTS
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__72046301__000
#     run: 0
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-4.0
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__72046301__001
#     run: 1
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-4.0
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__0c583243__000
#     run: 0
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-4.0
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__0c583243__001
#     run: 1
#     gnb_version:
#         type: srsRAN
#         uhd_version: UHD-4.0
#         version: release_24_10
#         commit: 9d5dd742a70e82c0813c34f57982f9507f1b6d5d
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__e5897d60__000
#     run: 0
#     gnb_version:
#         type: OAI
#         uhd_version: UHD-3.15.LTS
#         version: v2.2.0
#         commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__e5897d60__001
#     run: 1
#     gnb_version:
#         type: OAI
#         uhd_version: UHD-3.15.LTS
#         version: v2.2.0
#         commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
#     traffic_config:
#         traffic_type: iperfthroughput
#         direction: Ul
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '4455'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__2b4feae3__000
#     run: 0
#     gnb_version:
#         type: OAI
#         uhd_version: UHD-3.15.LTS
#         version: v2.2.0
#         commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
# -   identifier: 651c9a37__2b4feae3__001
#     run: 1
#     gnb_version:
#         type: OAI
#         uhd_version: UHD-3.15.LTS
#         version: v2.2.0
#         commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
#     traffic_config:
#         traffic_type: scapyudpping
#         direction: UlDl
#         traffic_duration: 60
#         proto: udp
#         dist: det
#         iat: '0.001'
#         rate: 100M
#         size: small
#         count: '60000'
#         target_ip: 10.45.0.1
#         target_port: '3344'
#         burst: '1'
#     tdd_config:
#         tdd_dl_ul_ratio: 2
#         tdd_flex_slots: 2
#         tdd_dl_ul_tx_period: 5
#         tdd_dl_slots: 3
#         tdd_dl_symbols: 8
#         tdd_ul_slots: 1
#         tdd_ul_symbols: 4
-   identifier: 651c9a37__ecc301b9__000
    run: 0
    gnb_version:
        type: OAI
        uhd_version: UHD-4.0
        version: v2.2.0
        commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
    traffic_config:
        traffic_type: iperfthroughput
        direction: Ul
        traffic_duration: 60
        proto: udp
        dist: det
        iat: '0.001'
        rate: 100M
        size: small
        count: '60000'
        target_ip: 10.45.0.1
        target_port: '4455'
        burst: '1'
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 8
        tdd_ul_slots: 1
        tdd_ul_symbols: 4
-   identifier: 651c9a37__ecc301b9__001
    run: 1
    gnb_version:
        type: OAI
        uhd_version: UHD-4.0
        version: v2.2.0
        commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
    traffic_config:
        traffic_type: iperfthroughput
        direction: Ul
        traffic_duration: 60
        proto: udp
        dist: det
        iat: '0.001'
        rate: 100M
        size: small
        count: '60000'
        target_ip: 10.45.0.1
        target_port: '4455'
        burst: '1'
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 8
        tdd_ul_slots: 1
        tdd_ul_symbols: 4
-   identifier: 651c9a37__a0a31b02__000
    run: 0
    gnb_version:
        type: OAI
        uhd_version: UHD-4.0
        version: v2.2.0
        commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
    traffic_config:
        traffic_type: scapyudpping
        direction: UlDl
        traffic_duration: 60
        proto: udp
        dist: det
        iat: '0.001'
        rate: 100M
        size: small
        count: '60000'
        target_ip: 10.45.0.1
        target_port: '3344'
        burst: '1'
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 8
        tdd_ul_slots: 1
        tdd_ul_symbols: 4
-   identifier: 651c9a37__a0a31b02__001
    run: 1
    gnb_version:
        type: OAI
        uhd_version: UHD-4.0
        version: v2.2.0
        commit: 68191088ab4cdcd47d6c0764ac5cf2483f4b3d29
    traffic_config:
        traffic_type: scapyudpping
        direction: UlDl
        traffic_duration: 60
        proto: udp
        dist: det
        iat: '0.001'
        rate: 100M
        size: small
        count: '60000'
        target_ip: 10.45.0.1
        target_port: '3344'
        burst: '1'
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 8
        tdd_ul_slots: 1
        tdd_ul_symbols: 4
