---

# requires following variables:
# srs_version
# gnb_bandwidth
# tdd_period
# tdd_dl_slots
# tdd_dl_symbols
# tdd_ul_slots
# tdd_ul_symbols


- name: "Edit srsRAN config: read config to variable"
  when: srs_version == "release_24_10"
  block:
     - ansible.builtin.slurp:
         path: ../config/gnb_config_baseline/srs.yml
       register: gnb_srs_config_content__24_10
       delegate_to: localhost
     - name: "Edit srsRAN config: parse variable to dict"
       ansible.builtin.set_fact:
         gnb_srs_config: "{{ gnb_srs_config_content__24_10['content'] | b64decode | from_yaml }}"
- name: "Edit srsRAN config: read config to variable"
  when: srs_version != "release_24_10"
  block:
     - ansible.builtin.slurp:
         path: ../config/gnb_config_baseline/srs_legacy.yml
       register: gnb_srs_config_content__legacy
       delegate_to: localhost
     - name: "Edit srsRAN config: parse variable to dict"
       ansible.builtin.set_fact:
         gnb_srs_config: "{{ gnb_srs_config_content__legacy['content'] | b64decode | from_yaml }}"


- name: "PRINT SRS CONFIG"
  ansible.builtin.debug:
    msg:
    - "{{ gnb_srs_config }}"

- name: "PRINT SRS CONFIG1"
  ansible.builtin.debug:
    msg:
    - "{{ gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.dl_ul_tx_period }}"
- name: "PRINT SRS CONFIG2"
  ansible.builtin.debug:
    msg:
    - "{{ item.tdd_config.tdd_period }}"

- name: "Set sampling rate"
  block:
  - ansible.builtin.set_fact:
      gnb_sampling_rate: 0 # catch missing/undefined bandwidth
  - ansible.builtin.set_fact:
      gnb_sampling_rate: 23.04
    when: item.gnb_bandwidth == "20"
  - ansible.builtin.set_fact:
      gnb_sampling_rate: 46.08
    when: item.gnb_bandwidth == "40"

- name: "Set MCS limits to temp variables"
  block:
    - ansible.builtin.set_fact:
        min_dl_mcs: 0
        max_dl_mcs: 28
      when: item.dl_mcs == "None"
    - ansible.builtin.set_fact:
        min_dl_mcs: "{{ item.dl_mcs }}"
        max_dl_mcs: "{{ item.dl_mcs }}"
      when: item.dl_mcs != "None"
    - ansible.builtin.set_fact:
        min_ul_mcs: 0
        max_ul_mcs: 28
      when: item.ul_mcs == "None"
    - ansible.builtin.set_fact:
        min_ul_mcs: "{{ item.ul_mcs }}"
        max_ul_mcs: "{{ item.ul_mcs }}"
      when: item.ul_mcs != "None"


    # Update fact is fucked, better try this: https://stackoverflow.com/a/67379573
- name: "Edit srsRAN config: update config"
  ansible.utils.update_fact:
    updates:
      - path: gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.dl_ul_tx_period
        value: "{{tdd_period}}"
      - path: gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.nof_dl_slots
        value: "{{tdd_dl_slots}}"
      - path: gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.nof_dl_symbols
        value: "{{tdd_dl_symbols}}"
      - path: gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.nof_ul_slots
        value: "{{tdd_ul_slots}}"
      - path: gnb_srs_config.cell_cfg.tdd_ul_dl_cfg.nof_ul_symbols
        value: "{{ tdd_ul_symbols }}"
      - path: gnb_srs_config.cell_cfg.channel_bandwidth_MHz
        value: "{{ gnb_bandwidth }}"
      - path: gnb_srs_config.ru_sdr.srate
        value: "{{ gnb_sampling_rate }}"
      - path: gnb_srs_config.cell_cfg.dl_arfcn
        value: "{{ bandwidth_definitions[item.gnb_bandwidth].srsRAN.dl_arfcn }}"
      - path: gnb_srs_config.cell_cfg.pusch.min_ue_mcs
        value: "{{ min_ul_mcs }}"
      - path: gnb_srs_config.cell_cfg.pusch.max_ue_mcs
        value: "{{ max_ul_mcs }}"
      - path: gnb_srs_config.cell_cfg.pdsch.min_ue_mcs
        value: "{{ min_dl_mcs }}"
      - path: gnb_srs_config.cell_cfg.pdsch.max_ue_mcs
        value: "{{ max_dl_mcs }}"
  register: gnb_srs_config_updated
  vars:  # temporary variables so we can actually cast to int # INFO: well, it doesn't work..
     # INFO: try these options next: https://stackoverflow.com/questions/69109062/cant-set-ansible-fact-as-integer https://serverfault.com/questions/1030350/converting-string-to-integer-in-ansible-playbook/1165629#1165629
    tdd_period: "{{ item.tdd_config.tdd_period | int }}"
    tdd_dl_slots:        "{{ item.tdd_config.tdd_dl_slots |int }}"
    tdd_dl_symbols:      "{{ item.tdd_config.tdd_dl_symbols |int }}"
    tdd_ul_slots:        "{{ item.tdd_config.tdd_ul_slots |int }}"
    tdd_ul_symbols:      "{{ item.tdd_config.tdd_ul_symbols |int }}"
    gnb_bandwidth:       "{{ item.gnb_bandwidth |int }}"
- ansible.builtin.set_fact:
    gnb_srs_config: "{{ gnb_srs_config_updated.gnb_srs_config }}"

- block:
  - name: "Edit srsRAN config: set rx gain"
    ansible.utils.update_fact:
       updates:
         - path: gnb_srs_config.ru_sdr.rx_gain
           value: "{{ item.rx_gain|int }}"
    register: gnb_srs_config_updated
  - ansible.builtin.set_fact:
      gnb_srs_config: "{{ gnb_srs_config_updated.gnb_srs_config }}"
  when: item.rx_gain != None
- block:
  - name: "Edit srsRAN config: set tx gain"
    ansible.utils.update_fact:
       updates:
         - path: gnb_srs_config.ru_sdr.tx_gain
           value: "{{ item.tx_gain|int }}"
    register: gnb_srs_config_updated
  - ansible.builtin.set_fact:
      gnb_srs_config: "{{ gnb_srs_config_updated.gnb_srs_config }}"
  when: item.tx_gain != None


- name: "PRINT SRS CONFIG"
  ansible.builtin.debug:
    msg:
    - "{{ gnb_srs_config }}"

- name: Write config back
  ansible.builtin.copy:
     content: "{{ gnb_srs_config | to_nice_yaml }}"
     dest: "{{ gnb_srs_config_path }}"
