# Branch names!
uhd_versions:
   - "UHD-4.0"
   # - "UHD-3.9.LTS" # BORKED?
   - "UHD-3.15.LTS"

# UHD version branch name, gitlab commit hash and related tag release name
oai_versions:
   - UHD: "UHD-4.0"
     OAI: "v2.4.0"
     commit: "91e7030cf8adefce502f0701fb7aaa1d512379df"
   - UHD: "UHD-4.0"
     OAI: "v2.3.0"
     commit: "8bf6d5d7da8c0a8384e4022fd4872e6d3d550921"
   - UHD: "UHD-4.0"
     OAI: "v2.2.0"
     commit: "68191088ab4cdcd47d6c0764ac5cf2483f4b3d29"
   - UHD: "UHD-4.0"
     OAI: "v2.1.0"
     commit: "9fab2124417cfe67fe09b1eab5e377e26c5cf3a5"

   - UHD: "UHD-3.15.LTS"
     OAI: "v2.2.0"
     commit: "68191088ab4cdcd47d6c0764ac5cf2483f4b3d29"
   - UHD: "UHD-3.15.LTS"
     OAI: "v2.1.0"
     commit: "9fab2124417cfe67fe09b1eab5e377e26c5cf3a5"

# UHD version branch name, github commit hash and related tag release name
srs_versions:
   - UHD: "UHD-4.0"
     SRS: "release_24_10"
     commit: "9d5dd742a70e82c0813c34f57982f9507f1b6d5d"
   - UHD: "UHD-4.0"
     SRS: "release_24_04"
     commit: "c33cacba7d940e734ac7bad08935cbc35578fad9"
   - UHD: "UHD-4.0"
     SRS: "modified_24_04"
     commit: "c33cacba7d940e734ac7bad08935cbc35578fad9"
     # Older
   - UHD: "UHD-4.0"
     SRS: "release_24_04"
     commit: "1483bda3091420cf7270eacdf31de932865c6294"

   - UHD: "UHD-3.15.LTS"
     SRS: "release_24_10"
     commit: "9d5dd742a70e82c0813c34f57982f9507f1b6d5d"
   - UHD: "UHD-3.15.LTS"
     SRS: "release_24_04"
     commit: "c33cacba7d940e734ac7bad08935cbc35578fad9"
     # Older
   - UHD: "UHD-3.15.LTS"
     SRS: "release_24_04"
     commit: "1483bda3091420cf7270eacdf31de932865c6294"


docker_tags:
  release_24_04:
    UHD-3.15: lkschu/srsran:24.04_3.15
    UHD-4.0: lkschu/srsran:24.04_4.0
  release_24_10:
    UHD-3.15: lkschu/srsran:24.10_3.15
    UHD-4.0: lkschu/srsran:24.10_4.0
  v2.1.0:
    UHD-3.15: lkschu/oai:2.1.0_3.15
    UHD-4.0: lkschu/oai:2.1.0_4.0
  v2.2.0:
    UHD-3.15: lkschu/oai:2.2.0_3.15
    UHD-4.0: lkschu/oai:2.2.0_4.0
