machines:
  hosts:
    5g-core:
      ansible_host: '172.16.32.51'
      ansible_user: 'core'
    5g-gnb:
      ansible_host: '172.16.32.50'
      ansible_user: 'gnb'
      uhd_version: 'UHD-4.0'
      ansible_python_interpreter: /usr/bin/python3.10
  vars:
    ansible_user: 'core'

