---

- name: Generate traffic
  hosts: 5g-gnb
  tasks:
    # - name: copy test 1
    #   ansible.builtin.fetch:
    #     src: /tmp/5ggnb-logs/
    #     dest: /tmp/
    #     flat: true
    #   delegate_to: 5g-core
    - name: copy to local
      ansible.builtin.fetch:
        src: /tmp/test/t1
        dest: /tmp/t1
        flat: true
      delegate_to: 5g-core
    - name: copy to target
      ansible.builtin.copy:
        src: /tmp/t1
        dest: "/home/gnb/t1"
      become: true

