---

- name: Install gnb
  hosts: 5g-gnb
  tasks:
    # INFO: debug print all available facts
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    - name: install uhd
      ansible.builtin.include_role:
        name: UHD
        tasks_from: main.yaml
    - name: install srs ran
      ansible.builtin.include_role:
        name: SRS
        tasks_from: main.yaml
    - name: install gnb measurement dependencies
      ansible.builtin.include_role:
        name: GNB-prerequisits
        tasks_from: main.yaml
