---

- name: Generate traffic
  hosts: 5g-gnb
  vars:
     icmp_intervall: "0.001"
     icmp_count: "60000"

     record_time: 60
     interface_ue: wwan0
     interface_gnb: eno1

     pcap_dump: ../dumps/

     gnb_srs_config_path: "/home/gnb/srsRAN-configs/gnb_rf_b200_tdd_n78_20mhz.yml"

  pre_tasks:
    - name: include test configuration
      include_vars: ../test.yaml


  tasks:

    # - name: Setting up smb mounts
    #   ansible.builtin.debug:
    #      msg:
    #      - "ID: {{ id }}"
    #      - "{{ tdd_config }}"
    #      - ""
    #   loop: "{{ run_to_run_variation }}"
    #   vars:
    #     id: "{{ item.identifier }}"
    #     tdd_config: "{{ item.tdd_config }}"


    - name: Run role
      ansible.builtin.include_role:
         name: debug
      loop: "{{ run_to_run_variation }}"



