---

- name: Generate traffic
  hosts: 5g-gnb
  vars:
    collected_logs: "/tmp/5ggnb-logs"
    gnb_srs_config_path: "/home/gnb/srsRAN-configs/gnb_srs.yml"
    gnb_srs_logfile_path: "/tmp/gnb.log"
    gnb_srs_binary: "/home/gnb/srsRAN_Project/build/apps/gnb/gnb"
    gnb_oai_config_path: "/home/gnb/OAI-configs/gnb_oai.conf"
    gnb_oai_logfile_path: "/tmp/gnb.log"
    gnb_oai_binary: "/home/gnb/openairinterface5g/cmake_targets/ran_build/build/nr-softmodem"
    snr_msm_script: "/home/gnb/read-snr.sh"
    snr_msm_script_output: "/tmp/modem-snr.csv"

  pre_tasks:
    - name: include docker tags map
      include_vars: ../config/gnb-versions.yaml
    - name: include test configuration
      # include_vars: ../first-tests-0.35h-scapy.yaml
      # include_vars: ../first-tests-0.35h-scapy-2.0.yaml
      # include_vars: ../compare-gnb-versions.yaml
      # include_vars: ../compare-gnb-versions-throughput.yaml
      # include_vars: ../compare-gnb-versions-throughput-jammer.yaml
      # include_vars: ../test.yaml
      # include_vars: ../antenna-gain-Dl.yaml
      # include_vars: ../throughput-uldl.yaml
      # include_vars: ../dockerization.yaml
      # include_vars: ../gnb-compare-delay.yaml
      # include_vars: ../throughput-overshoot.yaml
      # include_vars: ../throughput-overshoot-scapy.yaml
      # include_vars: ../throughput-overshoot-scapy_addruns_3.yaml
      # include_vars: ../perf-tuning.yaml
      include_vars: ../perf-tuning-on.yaml


  tasks:
     - name: iterate over test definition
       ansible.builtin.include_role:
          # name: measurement_main
          name: loop-control
       loop: "{{ run_to_run_variation }}"
       vars:
         docker_tags_map: "{{docker_tags}}"

