---

- name: Stop jammer wrapper service
  ansible.builtin.systemd:
    name: jammer-wrapper.service
    state: stopped
  become: true
  failed_when: false
  delegate_to: 5g-core

- name: Force jammer off
  ansible.builtin.uri:
    url: "http://127.0.0.1:5678/off"
    method: GET
    timeout: 2
  failed_when: false
  delegate_to: 5g-core

- name: Stop jammer API service
  ansible.builtin.systemd:
    name: jammer_api.service
    state: stopped
  become: true
  failed_when: false
  delegate_to: 5g-core
