# INFO: kill running OAI/SRS instances
- name: '"{{ item.identifier }}": killall running gnb instances'
  ansible.builtin.shell: |
     killall gnb || true
  become: true


# INFO: powercycle USB hub and wait!
- name: '"{{ item.identifier }}": powercycle modem'
  ansible.builtin.command:
    argv:
       - uhubctl
       - --action
       - cycle
       - --delay
       - 2
       - --location
       - 2-4
       - --location
       - 2-4.2
  become: true

# INFO: edit config and start gnb application and wait!
- name: '"{{ item.identifier }}": Run role'
  ansible.builtin.include_role:
    name: SRS_config
- name: Launch SRS gNB
  shell: "{{ gnb_srs_binary }} -c {{ gnb_srs_config_path }}"
  become: true
  async: 900
  poll: 0
  register: gnb_job

- name: '"{{ item.identifier }}": Wait for 60 seconds until gNB becomes ready'
  wait_for:
    timeout: 60

# INFO: Check if gnb is running
- name: '"{{ item.identifier }}": get gnb_job status'
  ansible.builtin.async_status:
    jid: "{{ gnb_job.ansible_job_id }}"
  register: gnb_job_results
  ignore_errors: true
  become: true
- block:
   - name: '"{{ item.identifier }}": job status of faulty run'
     debug:
        msg:
          - "{{ gnb_job_results }}"
   - name: '"{{ item.identifier }}": Copy gnb log of faulty run'
     ansible.builtin.fetch:
        src: "{{ gnb_srs_logfile_path }}"
        dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
        flat: true
        validate_checksum: false
     become: false
   - name: '"{{ item.identifier }}": Exit faulty run'
     ansible.builtin.meta: end_play
  when: gnb_job_results.failed != 0 or gnb_job_results.finished != 0



# INFO: get ip for modem
- name: '"{{ item.identifier }}": Acquire IP for modem'
  shell: "bash /home/gnb/setip.sh"
  become: true
- name: '"{{ item.identifier }}": Wait for 10 seconds after obtaining IP'
  wait_for:
    timeout: 10
# TODO: save gnb stdout/stderr on failure
# TODO: on failure: save stdout/stderr and gnb.log
# TODO: continue loop on failure
# TODO: track failed runs in evaluation?



- name: '"{{ item.identifier }}": tcpdump on gnb'
  ansible.builtin.command:
    cmd: sudo timeout {{ item.traffic_config.traffic_duration + 15 }} tcpdump -ni {{ system.fixed_params.interface_gnb }} --time-stamp-precision=nano -w /home/{{ ansible_user_id }}/tcpdump_gnb.pcap udp port 2152
  async: "{{ item.traffic_config.traffic_duration * 2 }}"
  poll: 0
  become: true
  register: tcpdump_gnb

- name: '"{{ item.identifier }}": tcpdump on ue'
  ansible.builtin.command:
    cmd: sudo timeout {{ item.traffic_config.traffic_duration + 15 }} tcpdump -ni {{ system.fixed_params.interface_ue }} --time-stamp-precision=nano -w /home/{{ ansible_user_id }}/tcpdump_ue.pcap
  async: "{{ item.traffic_config.traffic_duration * 2 }}"
  poll: 0
  become: true
  register: tcpdump_ue

- name: '"{{ item.identifier }}": sleep'
  ansible.builtin.command:
     cmd: sleep 2
  become: false

- name: '"{{ item.identifier }}": run ping role'
  ansible.builtin.include_role:
    name: measurements
    tasks_from: icmp.yaml
  vars:
    icmp_intervall: "{{ item.traffic_config.icmp_intervall }}"
    icmp_count: "{{ item.traffic_config.icmp_count }}"

- name: '"{{ item.identifier }}": wait for gnb tcpdump'
  ansible.builtin.async_status:
     jid: "{{ tcpdump_gnb.ansible_job_id }}"
  register: tcpdump_gnb_result
  until: tcpdump_gnb_result.finished
  failed_when: tcpdump_gnb_result.rc != 0 and tcpdump_gnb_result.rc != 124
  retries: 10
  delay: 5
  become: true

- name: '"{{ item.identifier }}": wait for ue tcpdump'
  ansible.builtin.async_status:
     jid: "{{ tcpdump_ue.ansible_job_id }}"
  register: tcpdump_ue_result
  until: tcpdump_ue_result.finished
  failed_when: tcpdump_gnb_result.rc != 0 and tcpdump_gnb_result.rc != 124
  retries: 10
  delay: 5
  become: true



# Copy pcaps and params to localhost
- name: "{{ item.identifier }}: Copy config to local: make dir"
  ansible.builtin.file:
     path: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
     state: directory
  delegate_to: localhost

# TODO: include start and end timestamp in yaml!!
- name: "{{ item.identifier }}: Copy config to local: copy"
  ansible.builtin.copy:
     content: "{{ system.fixed_params | ansible.builtin.combine( item ) }}"
     dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/{{ item.identifier }}.yaml"
  delegate_to: localhost

- name: '"{{ item.identifier }}": Copy gnb config'
  ansible.builtin.fetch:
     src: "{{ gnb_srs_config_path }}"
     dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
     flat: true
  become: false

- name: '"{{ item.identifier }}": Compress log'
  community.general.archive:
     path: "{{ gnb_srs_logfile_path }}"
     unsafe_writes: false
- name: '"{{ item.identifier }}": Copy gnb log'
  ansible.builtin.fetch:
     src: "{{ gnb_srs_logfile_path }}.gz"
     dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
     flat: true
     validate_checksum: false
  become: false

- name: '"{{ item.identifier }}": Compress pcaps (1/2)'
  community.general.archive:
     path: /home/{{ ansible_user_id }}/tcpdump_gnb.pcap
     unsafe_writes: false
     remove: true
     owner: "{{ ansible_user_id }}"
  become: true
- name: '"{{ item.identifier }}": Compress pcaps (2/2)'
  community.general.archive:
     path: /home/{{ ansible_user_id }}/tcpdump_ue.pcap
     unsafe_writes: false
     remove: true
     owner: "{{ ansible_user_id }}"
  become: true

- name: '"{{ item.identifier }}": Copy pcaps (1/2)'
  ansible.builtin.fetch:
     src: /home/{{ ansible_user_id }}/tcpdump_gnb.pcap.gz
     dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
     flat: true
  become: false
- name: '"{{ item.identifier }}": Copy pcaps (2/2)'
  ansible.builtin.fetch:
     src: /home/{{ ansible_user_id }}/tcpdump_ue.pcap.gz
     dest: "{{ system.pcap_dump }}/{{ system.identifier }}/{{ item.identifier }}/"
     flat: true
  become: false
- name: '"{{ item.identifier }}": Cleanup pcaps (1/2)'
  ansible.builtin.file:
     path: /home/{{ ansible_user_id }}/tcpdump_gnb.pcap.gz
     state: absent
  become: true
- name: '"{{ item.identifier }}": Cleanup pcaps (2/2)'
  ansible.builtin.file:
     path: /home/{{ ansible_user_id }}/tcpdump_ue.pcap.gz
     state: absent
  become: true

