system:
    pcap_dump: ../dumps/
    identifier: c80e840c
    fixed_params:
        distance_horizontal_in_m: 0.5
        distance_vertical_in_m: 0.0
        gnb_antenna_inclanation_in_degree: 90
        gnb_antenna_rotation_in_degree: 0
        ue_antenna_inclanation_in_degree: 90
        ue_antenna_rotation_in_degree: 0
        modem: SIM8200EA-M2 5G HAT
        interface_ue: wwan0
        interface_gnb: eno1
run_to_run_variation:
-   identifier: c80e840c__0
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 1
        tdd_flex_slots: 1
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 2
        tdd_dl_symbols: 8
        tdd_ul_slots: 2
        tdd_ul_symbols: 4
-   identifier: c80e840c__1
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 1
        tdd_flex_slots: 0
        tdd_dl_ul_tx_period: 10
        tdd_dl_slots: 5
        tdd_dl_symbols: 5
        tdd_ul_slots: 4
        tdd_ul_symbols: 7
-   identifier: c80e840c__2
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 1
        tdd_flex_slots: 0
        tdd_dl_ul_tx_period: 20
        tdd_dl_slots: 10
        tdd_dl_symbols: 5
        tdd_ul_slots: 9
        tdd_ul_symbols: 7
-   identifier: c80e840c__3
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 8
        tdd_ul_slots: 1
        tdd_ul_symbols: 4
-   identifier: c80e840c__4
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 1
        tdd_dl_ul_tx_period: 10
        tdd_dl_slots: 6
        tdd_dl_symbols: 8
        tdd_ul_slots: 3
        tdd_ul_symbols: 4
-   identifier: c80e840c__5
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 2
        tdd_flex_slots: 2
        tdd_dl_ul_tx_period: 20
        tdd_dl_slots: 13
        tdd_dl_symbols: 8
        tdd_ul_slots: 6
        tdd_ul_symbols: 4
-   identifier: c80e840c__6
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 4
        tdd_flex_slots: 0
        tdd_dl_ul_tx_period: 5
        tdd_dl_slots: 3
        tdd_dl_symbols: 12
        tdd_ul_slots: 1
        tdd_ul_symbols: 0
-   identifier: c80e840c__7
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 4
        tdd_flex_slots: 0
        tdd_dl_ul_tx_period: 10
        tdd_dl_slots: 7
        tdd_dl_symbols: 12
        tdd_ul_slots: 2
        tdd_ul_symbols: 0
-   identifier: c80e840c__8
    run: 1
    traffic_config:
        traffic_type: ping
        traffic_duration: 60
        icmp_intervall: 0.01
        icmp_count: 6000
    tdd_config:
        tdd_dl_ul_ratio: 4
        tdd_flex_slots: 0
        tdd_dl_ul_tx_period: 20
        tdd_dl_slots: 15
        tdd_dl_symbols: 12
        tdd_ul_slots: 4
        tdd_ul_symbols: 0
