---

# INFO: this task runs the python traffic generation
# WARNING: this requires a iperf3 server to be set up on the target(=core)


# {{ collected_logs }}/usb 2>&1"

- ansible.builtin.set_fact:
    iperf_shell_output: "{{ collected_logs | default('/tmp') }}/iperf"

- ansible.builtin.set_fact:
    iperf_udp: "--udp"
  when: tg_proto == 'udp'
- ansible.builtin.set_fact:
    iperf_udp: ""
  when: tg_proto != 'udp'

- ansible.builtin.set_fact:
    iperf_direction: "--reverse"
  when: tg_direction != 'Ul'
- ansible.builtin.set_fact:
    iperf_direction: ""
  when: tg_direction == 'Ul'

- name: Iperf3 traffic gen
  ansible.builtin.shell:
     cmd: "timeout {{ tg_duration + 10 }} iperf3 {{ iperf_udp }} {{ iperf_direction }} --port {{ tg_port }} --client {{ tg_ip }} --time {{ tg_duration }} --bitrate {{ tg_rate }} > {{ iperf_shell_output }} 2>&1"
  become: true
  ignore_errors: true
  register: iperf_ret

