---

# INFO: this task runs the python traffic generation
# WARNING: this requires a iperf3 server to be set up on the target(=core)


# TODO: redirect stdout/stderr to file and move to host
# TODO: when tg_proto == 'udp' ... else ...
# TODO: when direction == 'Ul' ... else ...
- name: Python traffic gen
  ansible.builtin.command:
     argv:
        - "iperf3"
        - "--udp"
        - "--port"
        - "{{ tg_port }}"
        - "--client"
        - "{{ tg_ip }}"
        - "--time"
        - "{{ tg_duration }}"
        - "--bitrate"
        - "{{ tg_rate }}"
        # - "{{ tg_size }}"
  become: true
