
---

# INFO: this task runs the python traffic generation
# WARNING: this requires a traffic sink to be set up on the target(=core), traffic sink should NOT answer (-a false)

- name: copy script
  ansible.builtin.copy:
    src: ../../../scripts/5g-scapy-client.py
    dest: /home/{{ ansible_user_id }}/5g-scapy-client.py
    mode: '755'
  become: false

- name: Python traffic gen
  ansible.builtin.shell:
    # cmd: "bash -c 'timeout {{ tg_duration }}s /home/{{ ansible_user_id }}/5g-scapy-client.py {{ tg_proto }} {{ tg_dist }} {{ tg_iat }} {{ tg_size }} {{ tg_count }} {{ tg_ip }} {{ tg_port }} {{ tg_burst }}  > {{ collected_logs }}/traffic_scapy 2>&1 || ( [[ $? -eq 124 ]] && true ) '"
    cmd: "timeout {{ tg_duration }}s /home/{{ ansible_user_id }}/5g-scapy-client.py {{ tg_proto }} {{ tg_dist }} {{ tg_iat }} {{ tg_size }} {{ tg_count }} {{ tg_ip }} {{ tg_port }} {{ tg_burst }}  > {{ collected_logs }}/traffic_scapy 2>&1"
  become: true
  register: scapy_udp_throughput_result
  failed_when: scapy_udp_throughput_result.rc != 0 and scapy_udp_throughput_result.rc != 124  # 124 is return code after timeout

#     tg_proto: "{{ item.traffic_config.scapy_proto }}"
#     tg_dist: "{{ item.traffic_config.scapy_dist }}"
#     tg_iat: "{{ item.traffic_config.scapy_iat }}"
#     tg_size: "{{ item.traffic_config.scapy_size }}"
#     tg_amount: "{{ item.traffic_config.scapy_amount }}"
#     tg_ip: "{{ item.traffic_config.scapy_ip }}"
#     tg_port: "{{ item.traffic_config.scapy_port }}"
#     tg_burst: "{{ item.traffic_config.scapy_burst }}"
