
# INFO: wrapper to allow continutation after a failed run.
#       If 'skip_until_id' is defined, all all runs will be skipped
#       until the run ID matches the 'skip_until_id'

# Only show once
- name: "{{ item.identifier }}: Show skip_until_id"
  ansible.builtin.debug:
    msg: "skip_until_id: {{ skip_until_id }}"
  when: skip_until_id is defined and is_running is undefined

- name: "{{ item.identifier }}: Set running true"
  ansible.builtin.set_fact:
    is_running: true
  when: is_running is undefined and skip_until_id is undefined
- name: "{{ item.identifier }}: Set running false"
  ansible.builtin.set_fact:
    is_running: false
  when: is_running is undefined and skip_until_id is defined


# Alles skippen
- name: "{{ item.identifier }}: Handle pcaps"
  when: is_running
  block:

    - name: "{{ item.identifier }}: iterate over test definition!"
      ansible.builtin.include_role:
        name: measurement_main
      # vars:
      #   docker_tags_map: "{{docker_tags_map_outer}}"

    - name: "{{ item.identifier }}: log task completion"
      ansible.builtin.include_role:
        name: monitoring
        tasks_from: logging.yaml
      vars:
        log_prefix: "COMPLETED"
        log_message: "{{ item.identifier }}"

# Change is running when tag is passed
- name: "{{ item.identifier }}: check for id"
  when: skip_until_id is defined and is_running == false and skip_until_id == item.identifier
  ansible.builtin.set_fact:
    is_running: true
